### ISSUE TITLE
What should I need to do for switch spark local to direct spark sql

### ISSUE THREAD

**Issue by RebieKong** [direct-spark-sql/direct-spark-sql#17]
My system is using a spark local instance for data works.
If I what to use this repo, what I need to do.
And if there are any feature is different between spark local and this.

**Comment by sleep-NULL** [comment]
You can use DirectSparkSession to build instance, it's provided some data register view function and sql execute function 
In our scenario, we need compute online feature for financial credit model so we need a high performance sql engine,
Spark original local mode use dag scheduler and task scheduler to split stage and execute task, and it's unnecessary exechange(shuffle) operator in local mode, we turn the original spark plan into direct plan we designed to skip scheduler execute overhead, and directly use scala Iterator to compute rather than use rdd.

**Comment by RebieKong** [comment]
u mean I can use it like a normal spark session, and all feature is works? or i just can use `spark.sql()`

**Comment by LaiZhou** [comment]
@RebieKong  spark.sqlDirectly("""
                                             |select
                                             |* from people t1
                                             |join people2 t2
                                             |on t1.name = t2.name
                                             |""".stripMargin)
